set_box_mode:
    name: Set BatteryBox Mode
    description: |
      Set the mode of the device.
      Please note upon successfully calling the service, it usually takes up to 10 minutes for the changes to be reflected 
      in the BBox and the UI, but occasionally may take up to an hour.
      You can check whether the call was successful in the OIG web or mobile app in the Notifications section.
    fields:
        Mode:
            description: The mode to set
            example: "Home 1"
            selector:
              select:
                options:
                  - "Home 1"
                  - "Home 2"
                  - "Home 3"
                  - "Home UPS"
        Acknowledgement:
            description: |
              I acknowledge that calling the service will result in parameter modification of a live system.
              I take on full responsibility for the changes and any effect they may have, expected or otherwise.
            selector:
              boolean: false

# set_grid_delivery:
#     description: Enable or disable grid delivery.
#     fields:
#         enabled:
#             description: True to enable, False to disable.
#             example: true
