"""Statistické senzory pro OIG Cloud integraci."""

from typing import Dict, Any

SENSOR_TYPES_STATISTICS: Dict[str, Dict[str, Any]] = {
    # Základní spotřeba - medián za posledních 10 minut
    "battery_load_median": {
        "name": "Aktuální medián spotřeby",
        "unit": "W",
        "icon": "mdi:chart-line",
        "device_class": "power",
        "state_class": "measurement",
        "sampling_minutes": 10,
        "statistic": "median",
    },
    # Víkend vs všední den spotřeba po časových úsecích
    "load_avg_6_8_weekday": {
        "name": "Průměrná spotřeba 6-8h (všední dny)",
        "unit": "W",
        "icon": "mdi:chart-timeline-variant",
        "device_class": "power",
        "state_class": "measurement",
        "time_range": (6, 8),
        "day_type": "weekday",
        "statistic": "median",
        "max_age_days": 30,
        "sampling_size": 1000,
    },
    "load_avg_8_12_weekday": {
        "name": "Průměrná spotřeba 8-12h (všední dny)",
        "unit": "W",
        "icon": "mdi:chart-timeline-variant",
        "device_class": "power",
        "state_class": "measurement",
        "time_range": (8, 12),
        "day_type": "weekday",
        "statistic": "median",
        "max_age_days": 30,
        "sampling_size": 1000,
    },
    "load_avg_12_16_weekday": {
        "name": "Průměrná spotřeba 12-16h (všední dny)",
        "unit": "W",
        "icon": "mdi:chart-timeline-variant",
        "device_class": "power",
        "state_class": "measurement",
        "time_range": (12, 16),
        "day_type": "weekday",
        "statistic": "median",
        "max_age_days": 30,
        "sampling_size": 1000,
    },
    "load_avg_16_22_weekday": {
        "name": "Průměrná spotřeba 16-22h (všední dny)",
        "unit": "W",
        "icon": "mdi:chart-timeline-variant",
        "device_class": "power",
        "state_class": "measurement",
        "time_range": (16, 22),
        "day_type": "weekday",
        "statistic": "median",
        "max_age_days": 30,
        "sampling_size": 1000,
    },
    "load_avg_22_6_weekday": {
        "name": "Průměrná spotřeba 22-6h (všední dny)",
        "unit": "W",
        "icon": "mdi:chart-timeline-variant",
        "device_class": "power",
        "state_class": "measurement",
        "time_range": (22, 6),  # přes půlnoc
        "day_type": "weekday",
        "statistic": "median",
        "max_age_days": 30,
        "sampling_size": 1000,
    },
    # Víkendové varianty
    "load_avg_6_8_weekend": {
        "name": "Průměrná spotřeba 6-8h (víkendy)",
        "unit": "W",
        "icon": "mdi:chart-timeline-variant",
        "device_class": "power",
        "state_class": "measurement",
        "time_range": (6, 8),
        "day_type": "weekend",
        "statistic": "median",
        "max_age_days": 30,
        "sampling_size": 1000,
    },
    "load_avg_8_12_weekend": {
        "name": "Průměrná spotřeba 8-12h (víkendy)",
        "unit": "W",
        "icon": "mdi:chart-timeline-variant",
        "device_class": "power",
        "state_class": "measurement",
        "time_range": (8, 12),
        "day_type": "weekend",
        "statistic": "median",
        "max_age_days": 30,
        "sampling_size": 1000,
    },
    "load_avg_12_16_weekend": {
        "name": "Průměrná spotřeba 12-16h (víkendy)",
        "unit": "W",
        "icon": "mdi:chart-timeline-variant",
        "device_class": "power",
        "state_class": "measurement",
        "time_range": (12, 16),
        "day_type": "weekend",
        "statistic": "median",
        "max_age_days": 30,
        "sampling_size": 1000,
    },
    "load_avg_16_22_weekend": {
        "name": "Průměrná spotřeba 16-22h (víkendy)",
        "unit": "W",
        "icon": "mdi:chart-timeline-variant",
        "device_class": "power",
        "state_class": "measurement",
        "time_range": (16, 22),
        "day_type": "weekend",
        "statistic": "median",
        "max_age_days": 30,
        "sampling_size": 1000,
    },
    "load_avg_22_6_weekend": {
        "name": "Průměrná spotřeba 22-6h (víkendy)",
        "unit": "W",
        "icon": "mdi:chart-timeline-variant",
        "device_class": "power",
        "state_class": "measurement",
        "time_range": (22, 6),
        "day_type": "weekend",
        "statistic": "median",
        "max_age_days": 30,
        "sampling_size": 1000,
    },
    # Solar Forecast senzor
    "solar_forecast": {
        "name": "Solar Forecast",
        "unit": "W",
        "icon": "mdi:solar-power",
        "device_class": "power",
        "state_class": "measurement",
    },
    "solar_forecast_info": {
        "name": "Solar Forecast Info",
        "unit": None,
        "icon": "mdi:information",
        "device_class": None,
        "state_class": None,
    },
    # Predikční senzory
    "battery_prediction_discharge_time": {
        "name": "Predikce - doba vybití baterie",
        "unit": "h",
        "icon": "mdi:battery-clock",
        "device_class": None,
        "state_class": "measurement",
    },
    "battery_prediction_needed_capacity": {
        "name": "Predikce - potřebná kapacita baterie",
        "unit": "kWh",
        "icon": "mdi:battery-plus",
        "device_class": "energy",
        "state_class": "measurement",
    },
    "battery_prediction_morning_soc": {
        "name": "Predikce - stav baterie ráno",
        "unit": "%",
        "icon": "mdi:battery-clock-outline",
        "device_class": "battery",
        "state_class": "measurement",
    },
}
