from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import EntityCategory

from typing import Dict

SENSOR_TYPES_MISC: Dict[
    str,
    Dict[str, str | SensorDeviceClass | SensorStateClass | EntityCategory | list[str]],
] = {
    "device_lastcall": {
        "name": "Last Call",
        "name_cs": "Poslední komunikace",
        "device_class": SensorDeviceClass.TIMESTAMP,
        "unit_of_measurement": None,
        "node_id": "device",
        "node_key": "lastcall",
        "state_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "data",
    },
    "real_data_update": {
        "name": "Real Data Update",
        "name_cs": "Skutečná aktualizace dat",
        "device_class": SensorDeviceClass.TIMESTAMP,
        "unit_of_measurement": None,
        "state_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "computed",
    },
    "invertor_prm1_p_max_feed_grid": {
        "name": "Max Feed to Grid",
        "name_cs": "Maximální přetoky",
        "device_class": SensorDeviceClass.POWER,
        "unit_of_measurement": "W",
        "node_id": "invertor_prm1",
        "node_key": "p_max_feed_grid",
        "state_class": SensorStateClass.MEASUREMENT,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "data",
    },
    "invertor_prms_to_grid": {
        "name": "Grid Delivery",
        "name_cs": "Přetoky do sítě",
        "device_class": SensorDeviceClass.ENUM,
        "unit_of_measurement": None,
        "node_id": "invertor_prms",
        "node_key": "to_grid",
        "state_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "options": ["Vypnuto / Off", "Zapnuto / On", "S omezením / Limited"],
        "sensor_type_category": "data",
    },
    "installed_battery_capacity_kwh": {
        "name": "Installed Battery Capacity",
        "name_cs": "Baterie - instalovaná kapacita",
        "device_class": SensorDeviceClass.ENERGY,
        "unit_of_measurement": "Wh",
        "state_class": SensorStateClass.MEASUREMENT,
        "node_id": "box_prms",
        "node_key": "p_bat",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "data",
    },
    "installed_fve_power_wp": {
        "name": "Installed FVE Power",
        "name_cs": "FVE - Instalovaný výkon",
        "device_class": SensorDeviceClass.POWER,
        "unit_of_measurement": "Wp",
        "state_class": SensorStateClass.MEASUREMENT,
        "node_id": "box_prms",
        "node_key": "p_fve",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "data",
    },
    "box_prms_crct": {
        "name": "Distribution Emergency Control",
        "name_cs": "Krizové ovládání distribuce",
        "device_class": SensorDeviceClass.ENUM,
        "unit_of_measurement": None,
        "state_class": None,
        "node_id": "box_prms",
        "node_key": "crct",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "options": ["Vypnuto / Off", "Zapnuto / On"],
        "sensor_type_category": "data",
    },
}
