from typing import Dict, Any
from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.helpers.entity import EntityCategory
from homeassistant.const import (
    UnitOfElectricPotential,
    UnitOfElectricCurrent,
    PERCENTAGE,
    UnitOfTemperature,
    UnitOfEnergy,
)

SENSOR_TYPES_EXTENDED_BATT: Dict[str, Dict[str, Any]] = {
    "extended_battery_voltage": {
        "name": "Extended Battery Voltage",
        "name_cs": "Napětí baterie",
        "unit_of_measurement": UnitOfElectricPotential.VOLT,
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "node_id": None,
        "node_key": None,
        "sensor_type_category": "extended",
    },
    "extended_battery_current": {
        "name": "Extended Battery Current",
        "name_cs": "Proud baterie",
        "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "node_id": None,
        "node_key": None,
        "sensor_type_category": "extended",
    },
    "extended_battery_capacity": {
        "name": "Extended Battery Capacity",
        "name_cs": "Rozšířená kapacita baterie",
        "unit_of_measurement": PERCENTAGE,
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "node_id": None,
        "node_key": None,
        "sensor_type_category": "extended",
    },
    "extended_battery_temperature": {
        "name": "Extended Battery Temperature",
        "name_cs": "Teplota baterie",
        "unit_of_measurement": UnitOfTemperature.CELSIUS,
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "node_id": None,
        "node_key": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "extended",
    },
    "usable_battery_capacity": {
        "name": "Usable Battery Capacity",
        "name_cs": "Baterie - využitelná kapacita",
        "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.MEASUREMENT,
        "node_id": None,
        "node_key": None,
        "sensor_type_category": "computed",
    },
    "missing_battery_kwh": {
        "name": "Missing Energy to 100%",
        "name_cs": "Baterie - k nabití",
        "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.MEASUREMENT,
        "node_id": None,
        "node_key": None,
        "sensor_type_category": "computed",
    },
    "remaining_usable_capacity": {
        "name": "Remaining Usable Capacity",
        "name_cs": "Baterie - zbývající kapacita",
        "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.MEASUREMENT,
        "node_id": None,
        "node_key": None,
        "sensor_type_category": "computed",
    },
    "time_to_full": {
        "name": "Time to Full",
        "name_cs": "Baterie - plné nabití",
        "unit_of_measurement": None,
        "device_class": None,
        "state_class": None,
        "node_id": None,
        "node_key": None,
        "sensor_type_category": "computed",
    },
    "time_to_empty": {
        "name": "Time to Empty",
        "name_cs": "Baterie - do vybití",
        "unit_of_measurement": None,
        "device_class": None,
        "state_class": None,
        "node_id": None,
        "node_key": None,
        "sensor_type_category": "computed",
    },
}
