from typing import Any, Dict

from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import EntityCategory, UnitOfEnergy, UnitOfPower

SENSOR_TYPES_MISC: Dict[str, Dict[str, Any]] = {
    "device_lastcall": {
        "name": "Last Call",
        "name_cs": "Poslední komunikace",
        "device_class": SensorDeviceClass.TIMESTAMP,
        "unit_of_measurement": None,
        "node_id": "device",
        "node_key": "lastcall",
        "state_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "data",
        "device_mapping": "main",
        "local_entity_suffix": "tbl_device_lastcall",
    },
    "real_data_update": {
        "name": "Real Data Update",
        "name_cs": "Skutečná aktualizace dat",
        "device_class": SensorDeviceClass.TIMESTAMP,
        "unit_of_measurement": None,
        "state_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "computed",
        "device_mapping": "main",
        "local_entity_id": "sensor.oig_local_oig_proxy_proxy_status_last_data",
    },
    "invertor_prm1_p_max_feed_grid": {
        "name": "Max Feed to Grid",
        "name_cs": "Maximální přetoky",
        "device_class": SensorDeviceClass.POWER,
        "unit_of_measurement": UnitOfPower.WATT,
        "node_id": "invertor_prm1",
        "node_key": "p_max_feed_grid",
        "state_class": SensorStateClass.MEASUREMENT,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "data",
        "device_mapping": "main",
        "local_entity_suffix": "tbl_invertor_prm1_p_max_feed_grid",
    },
    "invertor_prms_to_grid": {
        "name": "Grid Delivery",
        "name_cs": "Přetoky do sítě",
        "device_class": SensorDeviceClass.ENUM,
        "unit_of_measurement": None,
        "node_id": "invertor_prms",
        "node_key": "to_grid",
        "state_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "options": ["Vypnuto / Off", "Zapnuto / On", "S omezením / Limited"],
        "sensor_type_category": "data",
        "device_mapping": "main",
        "local_entity_domains": ["sensor", "binary_sensor"],
        "local_value_map": {"on": 1, "off": 0},
        "local_entity_suffix": "tbl_invertor_prms_to_grid",
    },
    "installed_battery_capacity_kwh": {
        "name": "Installed Battery Capacity",
        "name_cs": "Baterie - instalovaná kapacita",
        "device_class": SensorDeviceClass.ENERGY,
        "unit_of_measurement": UnitOfEnergy.WATT_HOUR,
        "state_class": SensorStateClass.MEASUREMENT,
        "node_id": "box_prms",
        "node_key": "p_bat",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "data",
        "device_mapping": "main",
        "local_entity_suffix": "tbl_box_prms_p_bat",
    },
    "installed_fve_power_wp": {
        "name": "Installed FVE Power",
        "name_cs": "FVE - Instalovaný výkon",
        "device_class": SensorDeviceClass.POWER,
        "unit_of_measurement": "Wp",
        "state_class": SensorStateClass.MEASUREMENT,
        "node_id": "box_prms",
        "node_key": "p_fve",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "data",
        "device_mapping": "main",
        "local_entity_suffix": "tbl_box_prms_p_fve",
    },
    "box_prms_crct": {
        "name": "Distribution Emergency Control",
        "name_cs": "Krizové ovládání distribuce",
        "device_class": SensorDeviceClass.ENUM,
        "unit_of_measurement": None,
        "state_class": None,
        "node_id": "box_prms",
        "node_key": "crct",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "options": ["Vypnuto / Off", "Zapnuto / On"],
        "sensor_type_category": "data",
        "device_mapping": "main",
        "local_entity_suffix": "tbl_box_prms_crct",
    },
    # Notification sensors - nová kategorie
    "latest_notification": {
        "name": "Latest Notification",
        "name_cs": "Poslední notifikace",
        "device_class": None,
        "unit_of_measurement": None,
        "state_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "notification",
        "device_mapping": "main",
        "icon": "mdi:bell",
    },
    "bypass_status": {
        "name": "Bypass Status",
        "name_cs": "Stav bypassu",
        "device_class": SensorDeviceClass.ENUM,
        "unit_of_measurement": None,
        "state_class": None,
        "entity_category": EntityCategory.DIAGNOSTIC,
        # Dashboard/UI expects "on"/"off" strings (also used by cloud notifications parser)
        "options": ["off", "on"],
        "sensor_type_category": "notification",
        "device_mapping": "main",
        "icon": "mdi:power-settings",
        "local_entity_suffix": "tbl_box_prms_bypass",
    },
    "notification_count_error": {
        "name": "Error Notifications Count",
        "name_cs": "Počet chybových notifikací",
        "device_class": None,
        "unit_of_measurement": "notifications",
        "state_class": SensorStateClass.MEASUREMENT,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "notification",
        "device_mapping": "main",
        "icon": "mdi:alert-circle",
    },
    "notification_count_warning": {
        "name": "Warning Notifications Count",
        "name_cs": "Počet varovných notifikací",
        "device_class": None,
        "unit_of_measurement": "notifications",
        "state_class": SensorStateClass.MEASUREMENT,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "notification",
        "device_mapping": "main",
        "icon": "mdi:alert",
    },
    "notification_count_unread": {
        "name": "Unread Notifications Count",
        "name_cs": "Počet nepřečtených notifikací",
        "device_class": None,
        "unit_of_measurement": "notifications",
        "state_class": SensorStateClass.MEASUREMENT,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "notification",
        "device_mapping": "main",
        "icon": "mdi:bell-badge",
    },
}
