from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import EntityCategory, UnitOfEnergy, UnitOfPower

from typing import Dict, Any

SENSOR_TYPES_BOILER: Dict[str, Dict[str, Any]] = {
    "boiler_current_cbb_w": {
        "name": "Boiler - Current Energy (CBB)",
        "name_cs": "Bojler - Aktuální výkon (CBB)",
        "device_class": SensorDeviceClass.POWER,
        "unit_of_measurement": UnitOfPower.WATT,
        "node_id": "boiler",
        "node_key": "p",
        "state_class": SensorStateClass.MEASUREMENT,
        "requires": ["boiler"],
        "sensor_type_category": "data",
    },
    "boiler_current_w": {
        "name": "Boiler - Current Energy (Computed)",
        "name_cs": "Bojler - Aktuální výkon (Vypočítaná)",
        "device_class": SensorDeviceClass.POWER,
        "unit_of_measurement": UnitOfPower.WATT,
        "node_id": None,
        "node_key": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "requires": ["boiler"],
        "sensor_type_category": "computed",
    },
    "boiler_day_w": {
        "name": "Boiler - Today Energy",
        "name_cs": "Bojler - Dnešní uložení",
        "device_class": SensorDeviceClass.POWER,
        "unit_of_measurement": UnitOfEnergy.WATT_HOUR,
        "node_id": "boiler",
        "node_key": "w",
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "requires": ["boiler"],
        "sensor_type_category": "data",
    },
    "boiler_manual_mode": {
        "name": "Boiler - Manual mode",
        "name_cs": "Bojler - Manuální režim",
        "device_class": SensorDeviceClass.ENUM,
        "unit_of_measurement": None,
        "node_id": "boiler_prms",
        "node_key": "manual",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "state_class": None,
        "options": ["Vypnuto / Off", "Zapnuto / On"],
        "sensor_type_category": "data",
    },
    "boiler_ssr1": {
        "name": "Boiler - SSR Rele 1",
        "name_cs": "Bojler - SSR Relé 1",
        "device_class": SensorDeviceClass.ENUM,
        "unit_of_measurement": None,
        "node_id": "boiler_prms",
        "node_key": "ssr0",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "state_class": None,
        "options": ["Vypnuto / Off", "Zapnuto / On"],
        "sensor_type_category": "data",
    },
    "boiler_ssr2": {
        "name": "Boiler - SSR Rele 2",
        "name_cs": "Bojler - SSR Relé 2",
        "device_class": SensorDeviceClass.ENUM,
        "unit_of_measurement": None,
        "node_id": "boiler_prms",
        "node_key": "ssr1",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "state_class": None,
        "options": ["Vypnuto / Off", "Zapnuto / On"],
        "sensor_type_category": "data",
    },
    "boiler_ssr3": {
        "name": "Boiler - SSR Rele 3",
        "name_cs": "Bojler - SSR Relé 3",
        "device_class": SensorDeviceClass.ENUM,
        "unit_of_measurement": None,
        "node_id": "boiler_prms",
        "node_key": "ssr2",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "state_class": None,
        "options": ["Vypnuto / Off", "Zapnuto / On"],
        "sensor_type_category": "data",
    },
    "boiler_is_use": {
        "name": "Boiler - is use",
        "name_cs": "Bojler - K dispozici",
        "device_class": SensorDeviceClass.ENUM,
        "unit_of_measurement": None,
        "node_id": "boiler_prms",
        "node_key": "ison",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "state_class": None,
        "options": ["Vypnuto / Off", "Zapnuto / On"],
        "sensor_type_category": "data",
    },
    "boiler_install_power": {
        "name": "Boiler - install power",
        "name_cs": "Bojler - instalovaný výkon",
        "device_class": SensorDeviceClass.POWER,
        "unit_of_measurement": UnitOfPower.WATT,
        "state_class": SensorStateClass.MEASUREMENT,
        "node_id": "boiler_prms",
        "node_key": "p_set",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "data",
    },
}
