from typing import Any, Dict

from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import PERCENTAGE, UnitOfEnergy, UnitOfPower
from homeassistant.helpers.entity import EntityCategory

SENSOR_TYPES_BATT: Dict[str, Dict[str, Any]] = {
    # Live hodnoty
    "batt_bat_c": {
        "name": "Battery Percent",
        "name_cs": "Nabití baterie (procenta, live)",
        "device_class": SensorDeviceClass.BATTERY,
        "unit_of_measurement": PERCENTAGE,
        "node_id": "actual",
        "node_key": "bat_c",
        "local_entity_suffix": "tbl_actual_bat_c",
        "state_class": SensorStateClass.MEASUREMENT,
        "sensor_type_category": "data",
        "device_mapping": "main",
    },
    "batt_batt_comp_p": {
        "name": "Battery Power",
        "name_cs": "Výkon baterie (live)",
        "device_class": SensorDeviceClass.POWER,
        "unit_of_measurement": UnitOfPower.WATT,
        "node_id": "actual",
        "node_key": "bat_p",
        "local_entity_suffix": "tbl_actual_bat_p",
        "state_class": SensorStateClass.MEASUREMENT,
        "sensor_type_category": "data",
        "device_mapping": "main",
    },
    "batt_bat_min": {
        "name": "Battery Minimum SOC",
        "name_cs": "Minimální nabití baterie (nastavení)",
        "device_class": SensorDeviceClass.BATTERY,
        "unit_of_measurement": PERCENTAGE,
        "node_id": "batt_prms",
        "node_key": "bat_min",
        "local_entity_suffix": "tbl_batt_prms_bat_min",
        "state_class": SensorStateClass.MEASUREMENT,
        "entity_category": EntityCategory.DIAGNOSTIC,
        "sensor_type_category": "data",
        "device_mapping": "main",
    },
    # Výkon oddělený na nabíjení a vybíjení
    "batt_batt_comp_p_charge": {
        "name": "Battery Charge Power",
        "name_cs": "Výkon baterie - nabíjení (live)",
        "device_class": SensorDeviceClass.POWER,
        "unit_of_measurement": UnitOfPower.WATT,
        "node_id": None,
        "node_key": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "sensor_type_category": "computed",
        "device_mapping": "main",
    },
    "batt_batt_comp_p_discharge": {
        "name": "Battery Discharge Power",
        "name_cs": "Výkon baterie - vybíjení (live)",
        "device_class": SensorDeviceClass.POWER,
        "unit_of_measurement": UnitOfPower.WATT,
        "node_id": None,
        "node_key": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "sensor_type_category": "computed",
        "device_mapping": "main",
    },
    # Energie nabíjení/vybíjení CELKEM
    "computed_batt_charge_energy_today": {
        "name": "Battery Charge Energy Today",
        "name_cs": "Energie nabíjení baterie dnes",
        "device_class": SensorDeviceClass.ENERGY,
        "unit_of_measurement": UnitOfEnergy.WATT_HOUR,
        "node_id": None,
        "node_key": None,
        "state_class": SensorStateClass.TOTAL,
        "sensor_type_category": "computed",
        "device_mapping": "main",
        "local_entity_suffix": "tbl_batt_bat_apd",
    },
    "computed_batt_discharge_energy_today": {
        "name": "Battery Discharge Energy Today",
        "name_cs": "Energie vybíjení baterie dnes",
        "device_class": SensorDeviceClass.ENERGY,
        "unit_of_measurement": UnitOfEnergy.WATT_HOUR,
        "node_id": None,
        "node_key": None,
        "state_class": SensorStateClass.TOTAL,
        "sensor_type_category": "computed",
        "device_mapping": "main",
        "local_entity_suffix": "tbl_batt_bat_and",
    },
    "computed_batt_charge_energy_month": {
        "name": "Battery Charge Energy This Month",
        "name_cs": "Energie nabíjení baterie tento měsíc",
        "device_class": SensorDeviceClass.ENERGY,
        "unit_of_measurement": UnitOfEnergy.WATT_HOUR,
        "node_id": None,
        "node_key": None,
        "state_class": SensorStateClass.TOTAL,
        "sensor_type_category": "computed",
        "device_mapping": "main",
    },
    "computed_batt_discharge_energy_month": {
        "name": "Battery Discharge Energy This Month",
        "name_cs": "Energie vybíjení baterie tento měsíc",
        "device_class": SensorDeviceClass.ENERGY,
        "unit_of_measurement": UnitOfEnergy.WATT_HOUR,
        "node_id": None,
        "node_key": None,
        "state_class": SensorStateClass.TOTAL,
        "sensor_type_category": "computed",
        "device_mapping": "main",
    },
    "computed_batt_charge_energy_year": {
        "name": "Battery Charge Energy This Year",
        "name_cs": "Energie nabíjení baterie tento rok",
        "device_class": SensorDeviceClass.ENERGY,
        "unit_of_measurement": UnitOfEnergy.WATT_HOUR,
        "node_id": None,
        "node_key": None,
        "state_class": SensorStateClass.TOTAL,
        "sensor_type_category": "computed",
        "device_mapping": "main",
        "local_entity_suffix": "tbl_batt_bat_ad",
    },
    "computed_batt_discharge_energy_year": {
        "name": "Battery Discharge Energy This Year",
        "name_cs": "Energie vybíjení baterie tento rok",
        "device_class": SensorDeviceClass.ENERGY,
        "unit_of_measurement": UnitOfEnergy.WATT_HOUR,
        "node_id": None,
        "node_key": None,
        "state_class": SensorStateClass.TOTAL,
        "sensor_type_category": "computed",
        "device_mapping": "main",
        "local_entity_suffix": "tbl_batt_bat_am",
    },
    # Energie nabíjení Z FVE
    "computed_batt_charge_fve_energy_today": {
        "name": "Battery Charge Energy from Solar Today",
        "name_cs": "Energie nabíjení baterie ze slunce dnes",
        "device_class": SensorDeviceClass.ENERGY,
        "unit_of_measurement": UnitOfEnergy.WATT_HOUR,
        "node_id": None,
        "node_key": None,
        "state_class": SensorStateClass.TOTAL,
        "sensor_type_category": "computed",
        "device_mapping": "main",
        "local_entity_suffix": "tbl_batt_bat_ad",
    },
    "computed_batt_charge_fve_energy_month": {
        "name": "Battery Charge Energy from Solar This Month",
        "name_cs": "Energie nabíjení baterie ze slunce tento měsíc",
        "device_class": SensorDeviceClass.ENERGY,
        "unit_of_measurement": UnitOfEnergy.WATT_HOUR,
        "node_id": None,
        "node_key": None,
        "state_class": SensorStateClass.TOTAL,
        "sensor_type_category": "computed",
        "device_mapping": "main",
        "local_entity_suffix": "tbl_batt_bat_ad",
    },
    "computed_batt_charge_fve_energy_year": {
        "name": "Battery Charge Energy from Solar This Year",
        "name_cs": "Energie nabíjení baterie ze slunce tento rok",
        "device_class": SensorDeviceClass.ENERGY,
        "unit_of_measurement": UnitOfEnergy.WATT_HOUR,
        "node_id": None,
        "node_key": None,
        "state_class": SensorStateClass.TOTAL,
        "sensor_type_category": "computed",
        "device_mapping": "main",
        "local_entity_suffix": "tbl_batt_bat_am",
    },
    # Energie nabíjení ZE SÍTĚ
    "computed_batt_charge_grid_energy_today": {
        "name": "Battery Charge Energy from Grid Today",
        "name_cs": "Energie nabíjení baterie ze sítě dnes",
        "device_class": SensorDeviceClass.ENERGY,
        "unit_of_measurement": UnitOfEnergy.WATT_HOUR,
        "node_id": None,
        "node_key": None,
        "state_class": SensorStateClass.TOTAL,
        "sensor_type_category": "computed",
        "device_mapping": "main",
        "local_entity_suffix": "tbl_batt_bat_ad",
    },
    "computed_batt_charge_grid_energy_month": {
        "name": "Battery Charge Energy from Grid This Month",
        "name_cs": "Energie nabíjení baterie ze sítě tento měsíc",
        "device_class": SensorDeviceClass.ENERGY,
        "unit_of_measurement": UnitOfEnergy.WATT_HOUR,
        "node_id": None,
        "node_key": None,
        "state_class": SensorStateClass.TOTAL,
        "sensor_type_category": "computed",
        "device_mapping": "main",
        "local_entity_suffix": "tbl_batt_bat_am",
    },
    "computed_batt_charge_grid_energy_year": {
        "name": "Battery Charge Energy from Grid This Year",
        "name_cs": "Energie nabíjení baterie ze sítě tento rok",
        "device_class": SensorDeviceClass.ENERGY,
        "unit_of_measurement": UnitOfEnergy.WATT_HOUR,
        "node_id": None,
        "node_key": None,
        "state_class": SensorStateClass.TOTAL,
        "sensor_type_category": "computed",
        "device_mapping": "main",
        "local_entity_suffix": "tbl_batt_bat_ay",
    },
}
